---
title: "Análisis de Desempeño Estadístico Global"
format: html
---

## Librerías

```{r}
library(tidyverse)

theme_set(theme_light() +
            theme(legend.position = "bottom",
                  plot.title = element_text(hjust = 0.5),
                  plot.subtitle = element_text(hjust = 0.5)))
```

## Cargando Datos

```{r}
# data <- tidytuesdayR::tt_load(2025, week = 47)
data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-11-25/spi_indicators.csv')

data
```

```{r}
data_world <- geodata::world(path = "01-statistical_performance_indicators/03-data-map/") |>
  sf::st_as_sf() |>
  as_tibble()
```

## Meta - análisis

```{r}
df_metadata <- funModeling::df_status(data, print_results = FALSE)
df_metadata
```

- Variables de puntajes con missing, posiblemente por no recoger el dato en determinado año.

## Análisis de Datos

```{r}
cat_var <- df_metadata |>
  filter(type == "character") |>
  pull(variable)

num_var <- df_metadata |>
  filter(type == "numeric",
         variable != "year") |>
  pull(variable)
```

### Univariado

Tomaremos como muestra el periodo del 2023

#### Variables Categóricas

```{r}
data |>
  filter(year == 2023) |>
  count(income, sort = TRUE)
```

```{r}
data |>
  filter(year == 2023) |>
  count(region)
```

#### Variables Numéricas

```{r}
data |>
  filter(year == 2023) |>
  ggplot(aes(population)) +
  geom_histogram()

matriz_histogramas(data |> filter(year == 2023), num_var)
```


```{r}
data |>
  filter(year == 2020)

data_world |>
  left_join(data |> filter(year == 2023),
            by = c("GID_0" = "iso3c")) |>
  ggplot() +
  geom_sf(aes(geometry = geometry, fill = overall_score)) +
  scale_fill_viridis_c() +
  theme_void() +
  theme(legend.position = "bottom")
```

## Evolutivo Global de Indicadores de Desempeño Estadístico

```{r}
library(gganimate)
```

```{r}
world_animation <- data_world |>
  left_join(data,
            by = c("GID_0" = "iso3c")) |>
  mutate(year = as.integer(year)) |>
  ggplot() +
  geom_sf(aes(geometry = geometry, fill = overall_score)) + 
  scale_fill_viridis_c() +
  labs(title = "Año: {frame_time}",
       fill = "Puntaje de desempeño estadístico") +
  theme_void() +
  theme(legend.position = "bottom") + 
  gganimate::transition_time(time = year) +
  ease_aes('linear')

world_animation
```

```{r}
animate(world_animation, height = 500, width = 800, res = 150)
anim_save(
  here::here("01-statistical_performance_indicators/02-outputs", "world_animation.gif")
)
```





